return {
  lua = require("filetypes/lua"),
  c = require("filetypes/c"),
  cpp = require("filetypes/cpp"),
  css = require("filetypes/css"),
  rust = require("filetypes/rust"),
  python = require("filetypes/python"),
  deno = require("filetypes/deno"),
  typescript = require("filetypes/typescript"),
  zig = require("filetypes/zig"),
  dart = require("filetypes/dart"),
  php = require("filetypes/php"),
  svelte = require("filetypes/svelte"),
  csharp = require("filetypes/csharp"),
  markdown = require("filetypes/markdown"),
  haskell = require("filetypes/haskell"),
  kotlin = require("filetypes/kotlin"),
  html = require("filetypes/html"),
  emmet = require("filetypes/emmet"),
}
